### ISSUE TITLE
QA Toolkit - Tracking - Requested Updates.docx

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#228]
The attached document has been developed to function as a continued reference for project team members to track updates requested from SHA, the prioritization that has been stated for beginning their development, and ultimately their final completion.

**Requested Updates.docx as of 2/9/2016:**
[Requested_Updates_20160208.pdf](https://github.com/BC89/sha_oed_issues/files/123524/Requested_Updates_20160208.pdf)

**Color coded priorities as defined within meeting taking place on 2/8/2016:**
![image](https://cloud.githubusercontent.com/assets/4098544/12925968/05e027ee-cf2f-11e5-9b88-48c4822224ac.png)

**Comment by slmessier** [comment]
fore reference, the original document from Tad has been attached. page 2 includes the referenced graphics, which are also described below: 
[KCI Task #7 list.docx](https://github.com/BC89/sha_oed_issues/files/127168/KCI.Task.7.list.docx)

![image](https://cloud.githubusercontent.com/assets/4098544/12992010/f0f39b24-d0df-11e5-8a1f-6e6dc49c756a.png)
![image](https://cloud.githubusercontent.com/assets/4098544/12992026/0329f0e0-d0e0-11e5-981a-51f36df65242.png)

![image](https://cloud.githubusercontent.com/assets/4098544/12992036/229a8ed0-d0e0-11e5-8924-7549209a45eb.png)
![image](https://cloud.githubusercontent.com/assets/4098544/12992031/0f48e156-d0e0-11e5-93ce-515538f44358.png)

![image](https://cloud.githubusercontent.com/assets/4098544/12992045/29e77d6a-d0e0-11e5-8e25-610aab2829dd.png)
![image](https://cloud.githubusercontent.com/assets/4098544/12992035/19e4236e-d0e0-11e5-8aa7-99cc791e31b5.png)

**Comment by slmessier** [comment]
- [x] Green No. 7 – GH Issue #218 
- [ ] Green No. 8 – GH Issue #195
- [ ] Green No. 9 – GH Issue #230
- [x] Green No. 10 – discussion in 2/8/2016 meeting determined that this update has already been implemented and that the request can be otherwise discarded since no additional development is required.
- [ ] Green No. 11
- [ ] Green No. 12 – GH Issue #225 
- [ ] Green No. 13

**Comment by slmessier** [comment]
![image](https://cloud.githubusercontent.com/assets/4098544/13086589/dd4f99d0-d4b1-11e5-8e45-e121180877de.png)
- [ ] Purple No. 2 – 
- [ ] Purple No. 3 – 
- [ ] Purple No. 4 – 
- [ ] Purple No. 5 – 
- [ ] Purple No. 6 –

**Comment by slmessier** [comment]
![image](https://cloud.githubusercontent.com/assets/4098544/13086688/4ae29baa-d4b2-11e5-9eea-39e06acfc0cb.png)

**Comment by slmessier** [comment]
![image](https://cloud.githubusercontent.com/assets/4098544/13086701/59ff45ac-d4b2-11e5-9862-6084b8d5d39d.png)

**Comment by slmessier** [comment]
![image](https://cloud.githubusercontent.com/assets/4098544/13086708/62538d4e-d4b2-11e5-8118-7b8cc6708bb4.png) - _Priority group 5 of 6_

**Comment by slmessier** [comment]
![image](https://cloud.githubusercontent.com/assets/4098544/13086861/21b7900e-d4b3-11e5-8d43-59679b960d06.png)
- [ ] Red No. 24 – 
- [ ] Red No. 25 – 
- [ ] Red No. 26 –
