### ISSUE TITLE
Task #8 Full list

### ISSUE THREAD

**Issue by rwingender** [kcigeospatial/sha_oed_issues#255]
**Task 8 - Tracking systems. (To be completed by June 30, 2016)** 

**1. Enhance the existing Permit Tracking System:  Enhance the current permit system within the toolkit.** 
a) Include 3 month notifications prior to expiration along with the existing 6 month notification. Update the email notification.  Ensure that the notification system is functioning correctly, currently the email notification is not functioning 
b) Enhance current system to differentiate between expired and active permits, update search filters accordingly. 
c) Limit the ability to add new permits to the roles of “ESC Manager, Project Manager and Inspector” 
d) Update buttons in the GUI under the permits tab to those supplied.  

**2. Develop a new Yellow card certification tracking system:  Develop a system to store and track Yellow card certifications.**
a) This should be listing “YC Cert” that can be printed based on search criteria (district, company, name, date, card number). 
b) The information in the “YC Cert” list is to be accessible by the Inspector, Project Manager and ESC Manager profiles. The list will include first name, last name, email, profile, expiration date, YC number) 
c) The certification number and expiration date should be entered as part of the users profile and appear in the user settings section. 
d) Add the YC and Exp date fields into the project record for the Project Rep and the Superintendent. 
e) Update the project record to have a dropdown box as part of the Project Rep, ESC Manager and Superintendent sections so that the individual may be selected form the user list based on profiles (Project Engineer or Contractor). When the drop down is utilized the YC cert and dates will be filled in accordingly. 
f) The system will automatically notify a user by email 3 months prior to certification expiration and highlight users when a certification has expired.  Highlight the individual in both the user account/list and in the project record. 
g) There should be the ability to revoke the certification from an individual by checking or selecting a box and imputing a reason into the account record.  This will show in the “YC Cert” listing.  

**3. Enhance the existing Incentive/Liquidated Damages tracking:  Enhance the existing Incentive/LD section of the project record.** 
a) Automate the incentive/LD section of the project record to fill in information and calculate the specified incentives or LD base in average inspection grades and Notice to Proceed.  The rules will be based upon those set in the construction specifications. 

**The following represents a detailed breakdown of specifications associated with "_3.Enhance the existing Incentive/Liquidated Damages tracking_"**
![image](https://cloud.githubusercontent.com/assets/4098544/15579872/80b70bf0-2334-11e6-846a-b7241c3ccdc7.png)
![image](https://cloud.githubusercontent.com/assets/4098544/15589217/e217b7f2-235f-11e6-837d-2d646a49234b.png)
![image](https://cloud.githubusercontent.com/assets/4098544/15589242/f54a8494-235f-11e6-9ccc-20fed4811d5a.png)
![image](https://cloud.githubusercontent.com/assets/4098544/15580001/fd411896-2334-11e6-8b7a-54909807ed4f.png)
![image](https://cloud.githubusercontent.com/assets/4098544/15580067/45ab9340-2335-11e6-8671-27c7e8fb6eb2.png)

**Comment by slmessier** [comment]
# Completion Tracking
![image](https://cloud.githubusercontent.com/assets/4098544/15580950/8b0e1590-2338-11e6-868e-e18be8ba513c.png)
- [ ] No. 1a – GH Issue #256  
- [ ] No. 1b – GH Issue #257  
- [ ] No. 1c – GH Issue #258  
- [ ] No. 1d – GH Issue #269
--------------------
![image](https://cloud.githubusercontent.com/assets/4098544/15580975/a5c1d368-2338-11e6-89d3-655bc7d39e7d.png)
- [ ] No. 2a – GH Issue #260 
- [ ] No. 2b – GH Issue #260 
- [ ] No. 2c – GH Issue #261 
- [ ] No. 2d – GH Issue #262
- [ ] No. 2e – GH Issue #262
- [ ] No. 2f – GH Issue #263 
- [ ] No. 2g – GH Issue #261 
--------------------
![image](https://cloud.githubusercontent.com/assets/4098544/15580905/6a3217a4-2338-11e6-8d9c-384192be037c.png)
- [ ] No. 3-1 – GH Issue #265
- [ ] No. 3-2 – GH Issue #266
- [ ] No. 3-3 – GH Issue #267
- [ ] No. 3-4 – GH Issue #268

**Comment by slmessier** [comment]
# Completion Tracking
![image](https://cloud.githubusercontent.com/assets/4098544/15580950/8b0e1590-2338-11e6-868e-e18be8ba513c.png)
- [ ] No. 1a – GH Issue #256  
- [x] No. 1b – GH Issue #257  
- [x] No. 1c – GH Issue #258  
- [x] No. 1d – GH Issue #269
--------------------
![image](https://cloud.githubusercontent.com/assets/4098544/15580975/a5c1d368-2338-11e6-89d3-655bc7d39e7d.png)
- [x] No. 2a – GH Issue #260 
- [x] No. 2b – GH Issue #260 
- [x] No. 2c – GH Issue #261 
- [ ] No. 2d – GH Issue #262
- [ ] No. 2e – GH Issue #262
- [ ] No. 2f – GH Issue #263 
- [ ] No. 2g – GH Issue #261 
--------------------
![image](https://cloud.githubusercontent.com/assets/4098544/15580905/6a3217a4-2338-11e6-8d9c-384192be037c.png)
- [ ] No. 3-1 – GH Issue #265
- [ ] No. 3-2 – GH Issue #266
- [ ] No. 3-3 – GH Issue #267
- [ ] No. 3-4 – GH Issue #268
