### ISSUE TITLE
QA Toolkit Task 19 - Update to SWM and Modification System - Master Tracker

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#391]
**This issue exists to function as a reliable reference point for project team members to track the completion of the enhancement requests associated with SHA OED Task 19.**

**Enhancement requests have been grouped and prioritized as listed below through collaborative meeting sessions between project team members and stakeholders.**

**Task 19 Scope of Work** (provided for reference purpose only; distinct requirements have been listed below)

[WO19 - Update to SWM and Modification System.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1860506/WO19.-.Update.to.SWM.and.Modification.System.pdf)

# Task 19 Enhancement Requests
![image](https://user-images.githubusercontent.com/25441512/38094296-6a46b366-333b-11e8-9704-856f31eaab9f.png)
![image](https://user-images.githubusercontent.com/25441512/38094314-754fc3ce-333b-11e8-8d13-4cddc2165e81.png)

**The three (3) GitHub Issues below represent the full specification associated with the Task 19 Request:**
- [x] GH Issue #388 - Update SWM As-Built Section
- [x] GH Issue #389 - Update Modification Section
- [x] GH Issue #390 - Updates to Both SWM and Modifications
