### ISSUE TITLE
QA Toolkit Task 20 - QA Toolkit Enhancements & - Master Tracker

### ISSUE THREAD

**Issue by HollySchuelerKCI** [kcigeospatial/sha_oed_issues#392]
This issue exists to function as a reliable reference point for project team members to track the completion of the enhancement requests associated with SHA OED Task 20.

Enhancement requests have been grouped and prioritized as listed below through collaborative meeting sessions between project team members and stakeholders.

Task 20 Scope of Work (provided for reference purpose only; distinct requirements have been listed below)

[WO20_ScopeOfWork_V2_20180305.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/1861321/WO20_ScopeOfWork_V2_20180305.pdf)

# Task 20 Enhancement Requests
![image](https://user-images.githubusercontent.com/25441512/38105231-7fc4039c-3359-11e8-90c0-cab47ef6f288.png)
![image](https://user-images.githubusercontent.com/25441512/38105245-8886ee04-3359-11e8-92ef-e32de34eef9b.png)
![image](https://user-images.githubusercontent.com/25441512/38105255-8fc3c980-3359-11e8-9fe1-8c366248f72a.png)
![image](https://user-images.githubusercontent.com/25441512/38105285-a5516b2c-3359-11e8-990e-c3d1c3aedb81.png)

**The three (3) GitHub Issues below represent the full specification associated with the Task 20 Request:**
- [ ] GH Issue #393 - Adjust Email Text for the Email Notification System
- [ ] GH Issue #394 -  Project Record Changes - Restrict Editing Ability on Fields
- [ ] GH Issue #395 -  Project Record Changes - Extend Width of Comments Input Field 
- [ ] GH Issue #396 - QA-1 / QA-2 Updates 
- [ ] GH Issue #397 - Touch Friendly GUI 
- [ ] GH Issue #398 -  Update QA Project Inspection by Date Report
- [ ] GH Issue #399 - Add Capability to Search Query for Projects Not Started
- [ ] GH Issue #400 - Automatically Associate a New Project to All Users with (2) Roles
- [ ] GH Issue #401 -  Update Button Graphics

**Comment by Tad-Daniel** [comment]
All items completed.  Item closed
