### ISSUE TITLE
OED Toolkit - Task 23 - Convert Reports to SSRS - Master Tracker

### ISSUE THREAD

**Issue by slmessier** [kcigeospatial/sha_oed_issues#423]
**This issue exists to function as a reliable reference point for project team members to track the completion of the enhancement requests associated with SHA OED Task 23.**

**Task 23 Scope of Work** (provided for reference purpose only; **report conversion requirements are listed below**)

[Work Order 23 - Final Work Move System In-House.pdf](https://github.com/kcigeospatial/sha_oed_issues/files/2368450/Work.Order.23.-.Final.Work.Move.System.In-House.pdf)

**The (48) GitHub Issues below represent the full specification associated with the Task 23 Request:**
### General Reports
- [x] GH Issue #448 - **G1 - ProjectSearch**
- [x] GH Issue #443 - **G2 - ProjectSearchCompany**
- [x] GH Issue #454 - **G3 - ProjectCommunicationReport**
- [x] GH Issue #445 - **G4 - ProjectDetails**
- [x] GH Issue #444 - **G5 - PPermitList**
- [x] GH Issue #441 - **G6 - PUserList**
### QA Toolkit
- [x] GH Issue #429 - **QA1 - InspectionSchedule**
- [x] GH Issue #430 - **QA2 - InspectionHold**
- [x] GH Issue #455 - **QA3 - QAInspections**
- [x] GH Issue #435 - **QA4 - QAInspectionGradeLog**
- [x] GH Issue #427 - **QA5 - QAInspectionLog**
- [x] GH Issue #428 - **QA6 - Inspection**
- [x] GH Issue #426  - **QA7 - InspectionQAOne**
- [x] GH Issue #456 - **QA8 - InspectionWeighted**
- [x] GH Issue #437 - **QA9 - PQA2List**
- [x] GH Issue #434 - **QA10 - QA2**
- [x] GH Issue #431 - **QA11 - QAInspectionPerDistrict**
- [x] GH Issue #438 - **QA12 - QAInspectionPerInspector**
- [x] GH Issue #433 - **QA13 - QAESCSummaryBPR**
- [x] GH Issue #439 - **QA14 - QANonComplFind**
- [x] GH Issue #425  - **QA15 - ESC Grade Summary**
- [x] GH Issue #432  - **QA16 - ModApproval**
- [x] GH Issue #432  - **QA17 - ModSummary**
- [x] GH Issue #440 - **QA18 - SWMList**
- [x] GH Issue #424 - **QA19 - YCCertList**
- [x] GH Issue #457 - **QA20 - ModReport**
- [x] GH Issue #458 - **QA21 - QA3**
- [x] GH Issue #459 - **QA22 - QA3Response**
- [x] GH Issue #436 - **QA23 - UserSubscriptions**
- [x] GH Issue #460 - **CAL1 - QA Calendar - Snapshot**
- [x] GH Issue #461 - **CAL2 - QA Calendar - Detailed PDF**
### IEM Toolkit
- [x] GH Issue #450 - **IEM1 - DailyInspectionListReport**
- [x] GH Issue #446 - **IEM2 - DailyInspectionReport**
- [x] GH Issue #447 - **IEM3 - DailyInspectionTemplate**
- [x] GH Issue #449  - **IEM4 - EnvironmanetalImapctReport**
- [x] GH Issue #451 - **IEM5 - IssInsp**
- [x] GH Issue #452 - **IEM6 - IssueDetailsReprt**
- [x] GH Issue #453 - **IEM7 - IssueSummaryReport**
- [x] GH Issue #442 - **IEM8 - ProjectStatus**
### MDE Toolkit
- [x] GH Issue #462 - **MDE1 - Accounting**
- [x] GH Issue #463 - **MDE2 - Current**
- [x] GH Issue #464 - **MDE3 - EPD**
- [x] GH Issue #472  - **MDE4 - EFP_NOPF**
- [x] GH Issue #465 - **MDE5 - EPDWorkload**
- [x] GH Issue #466 - **MDE6 - MDE**
- [x] GH Issue #467 - **MDE7 - PostPermitting**
- [x] GH Issue #468 - **MDE8 - TeamLeader**
- [x] GH Issue #471 - **MDE9 - Workload**
- [x] GH Issue #470 - **MDE10 - WorkloadEPD**
- [x] GH Issue #469 - **MDE11 - WOrkloadSRED**
